# Generated by Django 5.0.6 on 2024-05-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_models_alter_datasets_dataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='models',
            name='accuracy',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='models',
            name='matrix',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='models',
            name='report',
            field=models.TextField(default=None),
        ),
    ]
