# Generated by Django 5.0.6 on 2024-05-24 05:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_models_accuracy_models_matrix_models_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='models',
            name='visualization',
            field=models.FileField(default=None, upload_to='', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='models',
            name='model',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['pkl'])]),
        ),
    ]
